### ISSUE TITLE
Console.error -  Invariant failed: provided.innerRef has not been provided with a HTMLElement.

### ISSUE THREAD

**Issue by CandelariaParajon** [mikewuu/react-beautiful-dnd-tester#12]
I am getting this error when running my tests: 
`  console.error
    react-beautiful-dnd
    
    A setup problem was encountered.
    
    > Invariant failed: 
    provided.innerRef has not been provided with a HTMLElement.
    
    You can find a guide on using the innerRef callback functions at:
    https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md
    
    👷‍ This is a development only message. It will be removed in production builds.

      at log (node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:46:30)
      at node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:5533:9
      at invokePassiveEffectCreate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14504:20)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11391:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)`

I only get this error when running the tests that implement react-beautiful-dnd-tester, not when running the code. 
This error comes up every-time I try to use "verticalDrag".

**Comment by mikewuu** [comment]
Sorry, this package is no longer maintained. I recommend testing drag/drop via E2E tests in the browser as an alternative.
